Repository SOMNATH0904/DevSphere, pull requests merged in 2025-02, with the labels that each got.

#240 Added SimonSaysGame
  Project81 - SimonSaysGame/index.html
  Project81 - SimonSaysGame/script.js
  Project81 - SimonSaysGame/style.css
Labels: SWOC, INTERMEDIATE

#241 Project 81 : Wack_a_mole_game
  Project 81 - Wack_a_mole_Game/index.html
  Project 81 - Wack_a_mole_Game/mario-bg.jpg
  Project 81 - Wack_a_mole_Game/monty-mole.png
  Project 81 - Wack_a_mole_Game/pipe.png
  Project 81 - Wack_a_mole_Game/piranha-plant.png
  Project 81 - Wack_a_mole_Game/script.js
  Project 81 - Wack_a_mole_Game/soil.png
  Project 81 - Wack_a_mole_Game/style.css
Labels: SWOC, INTERMEDIATE

#245 Adding Voting Application Backend
  Project81 - Voting_Application_Backend/package-lock.json
  Project81 - Voting_Application_Backend/server/.gitignore
  Project81 - Voting_Application_Backend/server/VoteApp.drawio
  Project81 - Voting_Application_Backend/server/db.js
  Project81 - Voting_Application_Backend/server/jwt.js
  Project81 - Voting_Application_Backend/server/models/candidate.js
  Project81 - Voting_Application_Backend/server/models/user.js
  Project81 - Voting_Application_Backend/server/package-lock.json
  Project81 - Voting_Application_Backend/server/package.json
  Project81 - Voting_Application_Backend/server/routes/candidateRoutes.js
  Project81 - Voting_Application_Backend/server/routes/userRoutes.js
  Project81 - Voting_Application_Backend/server/server.js
Labels: SWOC, ADVANCE

#246 Add Car Racing game
  Project 81- car racing game/1.js
  Project 81- car racing game/1icon.png
  Project 81- car racing game/icon.png
  Project 81- car racing game/images/car04.png
  Project 81- car racing game/images/cloud.jpg
  Project 81- car racing game/images/finish.png
  Project 81- car racing game/images/hero.png
  Project 81- car racing game/images/tree.png
  Project 81- car racing game/index.html
  Project 81- car racing game/null.js
  Project 81- car racing game/style.css
Labels: SWOC, INTERMEDIATE

#249 added formify
  Project81 - formify/index.html
  Project81 - formify/script.js
  Project81 - formify/style.css
Labels: SWOC, INTERMEDIATE

#250 Added random choice picker
  Project81-RandomChoicePicker/index.html
  Project81-RandomChoicePicker/index.js
  Project81-RandomChoicePicker/style.css
Labels: SWOC, INTERMEDIATE

#251 recipe finder
  Project81-RecipeFinder/index.html
  Project81-RecipeFinder/index.js
  Project81-RecipeFinder/style.css
Labels: SWOC, INTERMEDIATE

#253 Add Space Ship Game
  Project  82-  Space Ship game/flappyBird_script.js
  Project  82-  Space Ship game/flappyBird_style.css
  Project  82-  Space Ship game/index.html
  Project  82-  Space Ship game/stars.js
Labels: SWOC, INTERMEDIATE

#254 Add Alien Catcher Game
  Project 83 - Alien Catcher Game/alien-catcher.css
  Project 83 - Alien Catcher Game/alien-catcher.html
  Project 83 - Alien Catcher Game/alien-catcher.js
  Project 83 - Alien Catcher Game/alien-image.png
  Project 83 - Alien Catcher Game/alien.png
  Project 83 - Alien Catcher Game/space.jpg
Labels: SWOC, INTERMEDIATE

#262 notes app added
  Project81 - NotesApp/index.html
  Project81 - NotesApp/script.js
  Project81 - NotesApp/style.css
Labels: SWOC, BEGINNER

#289 added temperature converter
  Project93-Temp_Converter/index.html
  Project93-Temp_Converter/index.js
  Project93-Temp_Converter/style.css
Labels: SWOC, BEGINNER

#290 added currency converter
  Project93-CurrencyConverter/index.html
  Project93-CurrencyConverter/script.js
  Project93-CurrencyConverter/style.css
Labels: SWOC, INTERMEDIATE

#292 added GitHub profile viewer
  Project93-GitHubProfileViewer/index.html
  Project93-GitHubProfileViewer/index.js
  Project93-GitHubProfileViewer/style.css
Labels: SWOC, BEGINNER

#293 added word guess game
  Project93-WordGuessGame/index.html
  Project93-WordGuessGame/index.js
  Project93-WordGuessGame/style.css
Labels: SWOC, BEGINNER

#297 Add Fun-Facts website
  Project93 - Fun-Facts/index.html
  Project93 - Fun-Facts/script.js
  Project93 - Fun-Facts/style.css
Labels: SWOC, BEGINNER

#300 Add Foodie Recipes App
  Project93 - Foodie Recepie App/.gitignore
  Project93 - Foodie Recepie App/README.md
  Project93 - Foodie Recepie App/index.html
  Project93 - Foodie Recepie App/package-lock.json
  Project93 - Foodie Recepie App/package.json
  Project93 - Foodie Recepie App/src/App.css
  Project93 - Foodie Recepie App/src/App.jsx
  Project93 - Foodie Recepie App/src/components/Container.jsx
  Project93 - Foodie Recepie App/src/components/FoodItem.jsx
  Project93 - Foodie Recepie App/src/components/FoodList.jsx
  Project93 - Foodie Recepie App/src/components/Fooddetail.jsx
  Project93 - Foodie Recepie App/src/components/Innerconatiner.jsx
  Project93 - Foodie Recepie App/src/components/Itemlist.jsx
  Project93 - Foodie Recepie App/src/components/Nav.jsx
  Project93 - Foodie Recepie App/src/components/Search.jsx
  Project93 - Foodie Recepie App/src/components/container.module.css
  Project93 - Foodie Recepie App/src/components/fooddetail.module.css
  Project93 - Foodie Recepie App/src/components/fooditem.module.css
  Project93 - Foodie Recepie App/src/components/innercontainer.module.css
  Project93 - Foodie Recepie App/src/components/nav.module.css
  Project93 - Foodie Recepie App/src/components/search.module.css
  Project93 - Foodie Recepie App/src/main.jsx
  Project93 - Foodie Recepie App/vite.config.js
Labels: SWOC, ADVANCE

#304 added analogue clock
  Project93-AnalogueClock/index.html
  Project93-AnalogueClock/index.js
  Project93-AnalogueClock/style.css
Labels: SWOC, INTERMEDIATE

#305 added math addition app
  Project93-MathAddition/index.html
  Project93-MathAddition/index.js
  Project93-MathAddition/style.css
Labels: SWOC, BEGINNER

#306 added number guessing game
  Project93-NumberGuessingGame/index.html
  Project93-NumberGuessingGame/index.js
  Project93-NumberGuessingGame/style.css
Labels: SWOC, BEGINNER

#312 Update script.js
  Project17 - GuessRandomNumberGame/script.js
Labels: SWOC, BEGINNER

#314 feat: random number guesser game
  Project93 - RandomNumberGuesser/index.html
  Project93 - RandomNumberGuesser/pl.png
  Project93 - RandomNumberGuesser/scripts.js
  Project93 - RandomNumberGuesser/style.css
Labels: SWOC, BEGINNER

#323 Add 3D Boxes Magic Background
  Project113 - 3d-boxes-background/index.html
  Project113 - 3d-boxes-background/script.js
  Project113 - 3d-boxes-background/style.css
Labels: SWOC, BEGINNER

#324 Add Animated Countdown
  Project113 - animated-countdown/index.html
  Project113 - animated-countdown/script.js
  Project113 - animated-countdown/style.css
Labels: SWOC, BEGINNER

#326 Pomodoro Timer
  Project113 - Pomodoro Timer/README.md
  Project113 - Pomodoro Timer/image.png
  Project113 - Pomodoro Timer/index.html
  Project113 - Pomodoro Timer/script.js
  Project113 - Pomodoro Timer/style.css
Labels: SWOC, INTERMEDIATE

#330 added greeting message
  Project113-GreetingMessage/index.html
  Project113-GreetingMessage/index.js
  Project113-GreetingMessage/style.css
Labels: SWOC, BEGINNER

#333 added background color switcher
  Project113-BackgroundColorSwitcher/index.html
  Project113-BackgroundColorSwitcher/index.js
  Project113-BackgroundColorSwitcher/style.css
Labels: SWOC, BEGINNER

#345 weather app added
  Project113 - WeatherApp/css/search.css
  Project113 - WeatherApp/css/style.css
  Project113 - WeatherApp/css/world.css
  Project113 - WeatherApp/img/cloud.png
  Project113 - WeatherApp/img/haze.png
  Project113 - WeatherApp/img/icon.png
  Project113 - WeatherApp/img/mist.png
  Project113 - WeatherApp/img/rain.png
  Project113 - WeatherApp/img/snow.png
  Project113 - WeatherApp/img/sun.png
  Project113 - WeatherApp/img/wind.png
  Project113 - WeatherApp/index.html
  Project113 - WeatherApp/js/config.js
  Project113 - WeatherApp/js/main.js
  Project113 - WeatherApp/js/search.js
  Project113 - WeatherApp/js/world.js
  Project113 - WeatherApp/search.html
  Project113 - WeatherApp/world.html
Labels: SWOC, INTERMEDIATE

#378 Card Matching Logic & Event Handling
  Project28 - MemoryMatchingGame/script.js
Labels: SWOC, BEGINNER

#379 Code Improvements for Flashcard App
  Project40 - FlashiThings/script.js
Labels: SWOC, BEGINNER

#381 added age calculator
  Project113-AgeCalculator/index.html
  Project113-AgeCalculator/index.js
  Project113-AgeCalculator/style.css
Labels: SWOC, BEGINNER

#382 meal finder added
  Project113 - MealFinder/index.html
  Project113 - MealFinder/script.js
  Project113 - MealFinder/style.css
Labels: SWOC, INTERMEDIATE

#391 added calendar app
  Project113-Calendar/index.html
  Project113-Calendar/index.js
  Project113-Calendar/style.css
Labels: SWOC, BEGINNER

#392 added to do list app
  Project113-ToDoList/index.html
  Project113-ToDoList/index.js
  Project113-ToDoList/style.css
Labels: SWOC, BEGINNER

#395 Robot joke generator
  Robot Joke Generator/index.html
  Robot Joke Generator/script.js
  Robot Joke Generator/style.css
Labels: SWOC, INTERMEDIATE

#405 Added Gym Website
  Project 86 - GymWebsite/assets/class-1.jpg
  Project 86 - GymWebsite/assets/class-2.jpg
  Project 86 - GymWebsite/assets/header.png
  Project 86 - GymWebsite/assets/join.jpg
  Project 86 - GymWebsite/assets/logo.png
  Project 86 - GymWebsite/assets/member.jpg
  Project 86 - GymWebsite/assets/men2-removebg-preview.png
  Project 86 - GymWebsite/index.html
  Project 86 - GymWebsite/styles.css
Labels: SWOC, ADVANCE

#407 Add Travel Website
  project 87 - TravelWebsite/assets/CSS/style.css
  project 87 - TravelWebsite/assets/Images/blog-bg copy.jpg
  project 87 - TravelWebsite/assets/Images/blog-bg.jpg
  project 87 - TravelWebsite/assets/Images/blog_1.jpg
  project 87 - TravelWebsite/assets/Images/blog_2 copy.jpg
  project 87 - TravelWebsite/assets/Images/blog_2.jpg
  project 87 - TravelWebsite/assets/Images/dest-1 copy.jpg
  project 87 - TravelWebsite/assets/Images/dest-1.jpg
  project 87 - TravelWebsite/assets/Images/dest-2 copy.jpg
  project 87 - TravelWebsite/assets/Images/dest-2.jpg
  project 87 - TravelWebsite/assets/Images/dest-3 copy.jpg
  project 87 - TravelWebsite/assets/Images/dest-3.jpg
  project 87 - TravelWebsite/assets/Images/dest-4 copy.jpg
  project 87 - TravelWebsite/assets/Images/dest-4.jpg
  project 87 - TravelWebsite/assets/Images/dest-5 copy.jpg
  project 87 - TravelWebsite/assets/Images/dest-5.jpg
  project 87 - TravelWebsite/assets/Images/gallery-1 copy.jpg
  project 87 - TravelWebsite/assets/Images/gallery-1.jpg
  project 87 - TravelWebsite/assets/Images/gallery-2 copy.jpg
  project 87 - TravelWebsite/assets/Images/gallery-2.jpg
  project 87 - TravelWebsite/assets/Images/gallery-3 copy.jpg
  project 87 - TravelWebsite/assets/Images/gallery-3.jpg
  project 87 - TravelWebsite/assets/Images/gallery-4 copy.jpg
  project 87 - TravelWebsite/assets/Images/gallery-4.jpg
  project 87 - TravelWebsite/assets/Images/gallery-5 copy.jpg
  project 87 - TravelWebsite/assets/Images/gallery-5.jpg
  project 87 - TravelWebsite/assets/Images/gallery-6 copy.jpg
  project 87 - TravelWebsite/assets/Images/gallery-6.jpg
  project 87 - TravelWebsite/assets/Images/gallery-bg.jpg
  project 87 - TravelWebsite/assets/Images/pexels-pixabay-163703.jpg
  project 87 - TravelWebsite/assets/Images/slide-bg-1.jpg
  project 87 - TravelWebsite/assets/Images/slide-bg-2.jpg
  project 87 - TravelWebsite/assets/Images/slide-bg-3.jpg
  project 87 - TravelWebsite/assets/Images/tour-1.jpg
  project 87 - TravelWebsite/assets/Images/tour-2.jpg
  project 87 - TravelWebsite/assets/Images/tour-3.jpg
  project 87 - TravelWebsite/assets/Images/tour-4.jpg
  project 87 - TravelWebsite/assets/Images/tour-5.jpg
  project 87 - TravelWebsite/assets/Images/tour-6.jpg
  project 87 - TravelWebsite/assets/Images/tour-7.jpg
  project 87 - TravelWebsite/assets/JS/script.js
  project 87 - TravelWebsite/index.html
  project 87 - TravelWebsite/index.txt
Labels: SWOC, INTERMEDIATE

#408 Add Maze Game
  Project 88 - Maze Game/home.png
  Project 88 - Maze Game/index.html
  Project 88 - Maze Game/key.png
  Project 88 - Maze Game/script.js
  Project 88 - Maze Game/style.css
Labels: SWOC, BEGINNER

#411 added heart trail animation
  HeartTrailAnimation/index.html
  HeartTrailAnimation/index.js
  HeartTrailAnimation/style.css
Labels: SWOC, BEGINNER

#413 added real time character counter
  RealTimeCharacterCounter/index.html
  RealTimeCharacterCounter/index.js
  RealTimeCharacterCounter/style.css
Labels: SWOC, BEGINNER

#414 added dice roll simulator
  DiceRollSimulator/index.html
  DiceRollSimulator/index.js
  DiceRollSimulator/style.css
Labels: SWOC, BEGINNER

#415 Quiz App
  project 90 - Quiz App/background_img.jpg
  project 90 - Quiz App/index.html
  project 90 - Quiz App/main.css
  project 90 - Quiz App/script.js
Labels: SWOC, INTERMEDIATE

#416 puzzle game
  Project 92 - 2D puzzle game/1 (1).jpg
  Project 92 - 2D puzzle game/1.jpg
  Project 92 - 2D puzzle game/10 (1).jpg
  Project 92 - 2D puzzle game/10.jpg
  Project 92 - 2D puzzle game/11.jpg
  Project 92 - 2D puzzle game/12.jpg
  Project 92 - 2D puzzle game/13.jpg
  Project 92 - 2D puzzle game/14.jpg
  Project 92 - 2D puzzle game/15.jpg
  Project 92 - 2D puzzle game/16.jpg
  Project 92 - 2D puzzle game/17.jpg
  Project 92 - 2D puzzle game/18.jpg
  Project 92 - 2D puzzle game/19.jpg
  Project 92 - 2D puzzle game/2 (1).jpg
  Project 92 - 2D puzzle game/2.jpg
  Project 92 - 2D puzzle game/20.jpg
  Project 92 - 2D puzzle game/21.jpg
  Project 92 - 2D puzzle game/22.jpg
  Project 92 - 2D puzzle game/23.jpg
  Project 92 - 2D puzzle game/24.jpg
  Project 92 - 2D puzzle game/25.jpg
  Project 92 - 2D puzzle game/26.jpg
  Project 92 - 2D puzzle game/3 (1).jpg
  Project 92 - 2D puzzle game/3.jpg
  Project 92 - 2D puzzle game/4 (1).jpg
  Project 92 - 2D puzzle game/4.jpg
  Project 92 - 2D puzzle game/5 (1).jpg
  Project 92 - 2D puzzle game/5.jpg
  Project 92 - 2D puzzle game/5_.jpg
  Project 92 - 2D puzzle game/6 (1).jpg
  Project 92 - 2D puzzle game/6.jpg
  Project 92 - 2D puzzle game/7 (1).jpg
  Project 92 - 2D puzzle game/7.jpg
  Project 92 - 2D puzzle game/8 (1).jpg
  Project 92 - 2D puzzle game/8.jpg
  Project 92 - 2D puzzle game/9 (1).jpg
  Project 92 - 2D puzzle game/9.jpg
  Project 92 - 2D puzzle game/background_img.jpg
  Project 92 - 2D puzzle game/index.html
  Project 92 - 2D puzzle game/logo.png
  Project 92 - 2D puzzle game/puzzle.css
  Project 92 - 2D puzzle game/puzzle.js
Labels: SWOC, BEGINNER

#419 Essay Writer
  project 92 -Essay Writing/css.css
  project 92 -Essay Writing/images/ui-icons_444444_256x240.png
  project 92 -Essay Writing/images/ui-icons_555555_256x240.png
  project 92 -Essay Writing/images/ui-icons_777620_256x240.png
  project 92 -Essay Writing/images/ui-icons_777777_256x240.png
  project 92 -Essay Writing/images/ui-icons_cc0000_256x240.png
  project 92 -Essay Writing/images/ui-icons_ffffff_256x240.png
  project 92 -Essay Writing/index.html
  project 92 -Essay Writing/jquery-3.3.1.min.js
  project 92 -Essay Writing/jquery-ui.css
  project 92 -Essay Writing/jquery-ui.min.js
  project 92 -Essay Writing/script.js
Labels: SWOC, INTERMEDIATE

#421 Motivational Quotes Generator
  project 93 -Quotes/index.html
  project 93 -Quotes/script.js
  project 93 -Quotes/style.css
  project 93 -Quotes/wallpaper.jpg
Labels: SWOC, BEGINNER

#424 Add Blog-Website
  project 93 -Blog website/about.png
  project 93 -Blog website/banner.png
  project 93 -Blog website/banner2 (1).png
  project 93 -Blog website/img1 (1).jpg
  project 93 -Blog website/img1.1.jpg
  project 93 -Blog website/img10.jpg
  project 93 -Blog website/img2 (1).jpg
  project 93 -Blog website/img3.jpg
  project 93 -Blog website/img4 (1).jpg
  project 93 -Blog website/img5 (1).jpg
  project 93 -Blog website/img6.jpg
  project 93 -Blog website/img7.jpg
  project 93 -Blog website/img8.jpg
  project 93 -Blog website/img9.jpg
  project 93 -Blog website/index.html
  project 93 -Blog website/main.js
  project 93 -Blog website/style.css
  project 93 -Blog website/testi1.jpg
  project 93 -Blog website/testi2.jpg
  project 93 -Blog website/testi3.jpg
Labels: SWOC, INTERMEDIATE

#429 Add Salon Website
  Project 90-Salon Website/assests/css/style.css
  Project 90-Salon Website/assests/img/about-img.jpg
  Project 90-Salon Website/assests/img/arabesco-left-bottom.svg
  Project 90-Salon Website/assests/img/arabesco-left-top.svg
  Project 90-Salon Website/assests/img/depoimentos/depoimento-1.png
  Project 90-Salon Website/assests/img/depoimentos/depoimento-2.png
  Project 90-Salon Website/assests/img/favicon.png
  Project 90-Salon Website/assests/img/home-img.png
  Project 90-Salon Website/assests/img/img-insta/foto1.png
  Project 90-Salon Website/assests/img/img-insta/foto2.png
  Project 90-Salon Website/assests/img/img-insta/foto3.png
  Project 90-Salon Website/assests/img/img-insta/foto4.png
  Project 90-Salon Website/assests/img/img-insta/foto5.png
  Project 90-Salon Website/assests/img/img-insta/foto6.png
  Project 90-Salon Website/assests/img/img-insta/foto7.png
  Project 90-Salon Website/assests/img/img-insta/foto8.png
  Project 90-Salon Website/assests/img/logo.svg
  Project 90-Salon Website/assests/img/servicos/corte.png
  Project 90-Salon Website/assests/img/servicos/depilacao.png
  Project 90-Salon Website/assests/img/servicos/limpeza.png
  Project 90-Salon Website/assests/img/servicos/manicure.png
  Project 90-Salon Website/assests/img/servicos/maquiagem.png
  Project 90-Salon Website/assests/img/servicos/pedicure.png
  Project 90-Salon Website/assests/img/servicos/pentado.png
  Project 90-Salon Website/assests/img/servicos/sobrancelha.png
  Project 90-Salon Website/assests/js/style.js
  Project 90-Salon Website/index.html
Labels: SWOC, ADVANCE

#431 Add Neon Glow Error Project
  Project122 - NeonGlowErrorPage/index.html
  Project122 - NeonGlowErrorPage/style.css
Labels: SWOC, INTERMEDIATE

#432 Add Card Styled Accordion Project
  Project123 - CardStyledAccordion/index.html
  Project123 - CardStyledAccordion/script.js
  Project123 - CardStyledAccordion/styles.css
Labels: SWOC, INTERMEDIATE

#433 Generate Certificate for Contributors
  Project 122- Devsphere Contributors/contributor.css
  Project 122- Devsphere Contributors/contributor.js
  Project 122- Devsphere Contributors/index.html
Labels: SWOC, ADVANCE

#434 Add Project Promptify
  Project122 - Promptify/.gitignore
  Project122 - Promptify/README.md
  Project122 - Promptify/app/api/auth/[...nextauth]/route.js
  Project122 - Promptify/app/api/prompt/[id]/route.js
  Project122 - Promptify/app/api/prompt/new/route.js
  Project122 - Promptify/app/api/prompt/route.js
  Project122 - Promptify/app/api/users/[id]/posts/route.js
  Project122 - Promptify/app/create-prompt/page.jsx
  Project122 - Promptify/app/favicon.ico
  Project122 - Promptify/app/layout.jsx
  Project122 - Promptify/app/page.jsx
  Project122 - Promptify/app/profile/[id]/page.jsx
  Project122 - Promptify/app/profile/loading.jsx
  Project122 - Promptify/app/profile/page.jsx
  Project122 - Promptify/app/update-prompt/page.jsx
  Project122 - Promptify/components/Feed.jsx
  Project122 - Promptify/components/Form.jsx
  Project122 - Promptify/components/Forms.jsx
  Project122 - Promptify/components/Nav.jsx
  Project122 - Promptify/components/Profile.jsx
  Project122 - Promptify/components/PromptCard.jsx
  Project122 - Promptify/components/Provider.jsx
  Project122 - Promptify/jsconfig.json
  Project122 - Promptify/models/prompt.js
  Project122 - Promptify/models/user.js
  Project122 - Promptify/next.config.js
  Project122 - Promptify/package-lock.json
  Project122 - Promptify/package.json
  Project122 - Promptify/postcss.config.js
  Project122 - Promptify/public/assets/icons/copy.svg
  Project122 - Promptify/public/assets/icons/link.svg
  Project122 - Promptify/public/assets/icons/loader.svg
  Project122 - Promptify/public/assets/icons/menu.svg
  Project122 - Promptify/public/assets/icons/tick.svg
  Project122 - Promptify/public/assets/images/grid.svg
  Project122 - Promptify/public/assets/images/logo-text.svg
  Project122 - Promptify/public/assets/images/logo.svg
  Project122 - Promptify/styles/globals.css
  Project122 - Promptify/tailwind.config.js
  Project122 - Promptify/utils/database.js
Labels: SWOC, ADVANCE

#436 Zombiee Shooter Game Added
  Project 123-Zombiee Shooter Game/index.html
  Project 123-Zombiee Shooter Game/script.js
  Project 123-Zombiee Shooter Game/style.css
Labels: SWOC, INTERMEDIATE

#461 Add Yoga Pose Guide Website
  project 121/assets/46-banner.png
  project 121/assets/classes-1.jpg
  project 121/assets/classes-2.jpg
  project 121/assets/classes-3.jpg
  project 121/assets/classes-4.jpg
  project 121/assets/classes-5.jpg
  project 121/assets/classes-6.jpg
  project 121/assets/header.jpg
  project 121/assets/icon-1.png
  project 121/assets/icon-2.png
  project 121/assets/icon-3.png
  project 121/assets/icon-4.png
  project 121/assets/logo.png
  project 121/assets/photos-1.jpg
  project 121/assets/photos-2.jpg
  project 121/assets/photos-3.jpg
  project 121/assets/photos-4.jpg
  project 121/assets/posts-1.jpg
  project 121/assets/posts-2.jpg
  project 121/assets/posts-3.jpg
  project 121/assets/stories-1.jpg
  project 121/assets/stories-2.jpg
  project 121/assets/stories-3.jpg
  project 121/assets/why.jpg
  project 121/index.html
  project 121/main.js
  project 121/styles.css
Labels: SWOC, INTERMEDIATE

#463 3D Among Us Game
  project 123/1.css
  project 123/asteroid_bg.png
  project 123/index.html
  project 123/script.js
  project 123/svg links.html
Labels: SWOC, ADVANCE

#471 Beauty Makeover Website
  Project 125/about.html
  Project 125/contact.html
  Project 125/css/MediaQuery.css
  Project 125/css/about.css
  Project 125/css/contact.css
  Project 125/css/porfolio.css
  Project 125/css/services.css
  Project 125/css/style.css
  Project 125/img/1.jpg
  Project 125/img/2.jpg
  Project 125/img/25off.png
  Project 125/img/3.jpg
  Project 125/img/4.jpg
  Project 125/img/5.jpg
  Project 125/img/6.jpg
  Project 125/img/7.jpg
  Project 125/img/FullySpa.jpg
  Project 125/img/GlitterBG-free-img.jpg
  Project 125/img/about_trans.svg
  Project 125/img/after1.jpg
  Project 125/img/after2.jpg
  Project 125/img/artist1.jpg
  Project 125/img/artist2.jpg
  Project 125/img/artist3.jpg
  Project 125/img/background180.svg
  Project 125/img/backgroundimg.jpg
  Project 125/img/before1.jpg
  Project 125/img/before2.jpg
  Project 125/img/bestbrindalOffer1.jpg
  Project 125/img/bestbrindalOffer2.jpg
  Project 125/img/bestbrindalOffer3.jpg
  Project 125/img/botox.jpg
  Project 125/img/botox_6.jpg
  Project 125/img/cosmeticStore.jpg
  Project 125/img/cosmetics_4.jpg
  Project 125/img/discountBackGround.jpg
  Project 125/img/discountimg.jpg
  Project 125/img/fullBodyMas.jpg
  Project 125/img/hair.jpg
  Project 125/img/haircut_2.jpg
  Project 125/img/home-model1.jpg
  Project 125/img/home-model2.jpg
  Project 125/img/home-model3.jpg
  Project 125/img/home-model4.jpg
  Project 125/img/logoParlour.png
  Project 125/img/massage_3.jpg
  Project 125/img/nailart_1.jpg
  Project 125/img/nails.jpg
  Project 125/img/profile-image.jpg
  Project 125/img/serviceBackGround.jpg
  Project 125/img/spa_5.jpg
  Project 125/img/test150x150.jpg
  Project 125/index.html
  Project 125/js/script.js
  Project 125/protfolio.html
  Project 125/services.html
Labels: SWOC, INTERMEDIATE

#498 Snake Game Fixed
  Project03 - SnakeGame/snake.html
Labels: SWOC, BEGINNER

#499 Slide Puzzle Game 3D
  Project 127-Slide Puzzle 3D Game/backspace.jpg
  Project 127-Slide Puzzle 3D Game/images/1.jpg
  Project 127-Slide Puzzle 3D Game/images/10.jpg
  Project 127-Slide Puzzle 3D Game/images/11.jpg
  Project 127-Slide Puzzle 3D Game/images/12.jpg
  Project 127-Slide Puzzle 3D Game/images/13.jpg
  Project 127-Slide Puzzle 3D Game/images/14.jpg
  Project 127-Slide Puzzle 3D Game/images/15.jpg
  Project 127-Slide Puzzle 3D Game/images/16.jpg
  Project 127-Slide Puzzle 3D Game/images/17.jpg
  Project 127-Slide Puzzle 3D Game/images/18.jpg
  Project 127-Slide Puzzle 3D Game/images/19.jpg
  Project 127-Slide Puzzle 3D Game/images/2.jpg
  Project 127-Slide Puzzle 3D Game/images/20.jpg
  Project 127-Slide Puzzle 3D Game/images/21.jpg
  Project 127-Slide Puzzle 3D Game/images/22.jpg
  Project 127-Slide Puzzle 3D Game/images/23.jpg
  Project 127-Slide Puzzle 3D Game/images/24.jpg
  Project 127-Slide Puzzle 3D Game/images/25.jpg
  Project 127-Slide Puzzle 3D Game/images/26.jpg
  Project 127-Slide Puzzle 3D Game/images/3.jpg
  Project 127-Slide Puzzle 3D Game/images/4.jpg
  Project 127-Slide Puzzle 3D Game/images/5.jpg
  Project 127-Slide Puzzle 3D Game/images/6.jpg
  Project 127-Slide Puzzle 3D Game/images/7.jpg
  Project 127-Slide Puzzle 3D Game/images/8.jpg
  Project 127-Slide Puzzle 3D Game/images/9.jpg
  Project 127-Slide Puzzle 3D Game/images/blank.jpg
  Project 127-Slide Puzzle 3D Game/images/blank2.jpg
  Project 127-Slide Puzzle 3D Game/index.html
  Project 127-Slide Puzzle 3D Game/puzzle.css
  Project 127-Slide Puzzle 3D Game/puzzle.js
Labels: SWOC, INTERMEDIATE

#502 Revolutionary Branded Watch Website
  Project 130- Revolutionary Branded Watch Website/assets/arrival-1.png
  Project 130- Revolutionary Branded Watch Website/assets/arrival-2.png
  Project 130- Revolutionary Branded Watch Website/assets/arrival-3.png
  Project 130- Revolutionary Branded Watch Website/assets/arrival-4.png
  Project 130- Revolutionary Branded Watch Website/assets/client-1.jpg
  Project 130- Revolutionary Branded Watch Website/assets/client-2.jpg
  Project 130- Revolutionary Branded Watch Website/assets/client-3.jpg
  Project 130- Revolutionary Branded Watch Website/assets/client.jpg
  Project 130- Revolutionary Branded Watch Website/assets/feature-1.png
  Project 130- Revolutionary Branded Watch Website/assets/feature-2.png
  Project 130- Revolutionary Branded Watch Website/assets/feature-3.png
  Project 130- Revolutionary Branded Watch Website/assets/header.png
  Project 130- Revolutionary Branded Watch Website/assets/logo-dark.png
  Project 130- Revolutionary Branded Watch Website/assets/logo-white.png
  Project 130- Revolutionary Branded Watch Website/assets/story.png
  Project 130- Revolutionary Branded Watch Website/index.html
  Project 130- Revolutionary Branded Watch Website/main.js
  Project 130- Revolutionary Branded Watch Website/styles.css
Labels: SWOC, BEGINNER

#519 Added Weebopedia
  Project139 - Weebopedia/.eslintrc.json
  Project139 - Weebopedia/.gitignore
  Project139 - Weebopedia/README.md
  Project139 - Weebopedia/app/[animeData]/page.jsx
  Project139 - Weebopedia/app/favicon.ico
  Project139 - Weebopedia/app/globals.css
  Project139 - Weebopedia/app/layout.jsx
  Project139 - Weebopedia/app/page.jsx
  Project139 - Weebopedia/components/AnimeCard.jsx
  Project139 - Weebopedia/components/AnimeDetail.jsx
  Project139 - Weebopedia/components/DoublePartition.jsx
  Project139 - Weebopedia/components/GenreSidebar.jsx
  Project139 - Weebopedia/components/Heading.jsx
  Project139 - Weebopedia/components/MainCrousel.jsx
  Project139 - Weebopedia/components/Navbar.jsx
  Project139 - Weebopedia/components/Seasonal.jsx
  Project139 - Weebopedia/components/TopAnime.jsx
  Project139 - Weebopedia/components/Upcoming.jsx
  Project139 - Weebopedia/jsconfig.json
  Project139 - Weebopedia/next.config.js
  Project139 - Weebopedia/package-lock.json
  Project139 - Weebopedia/package.json
  Project139 - Weebopedia/postcss.config.js
  Project139 - Weebopedia/public/assets/126627l.jpg
  Project139 - Weebopedia/public/assets/bleach.jpg
  Project139 - Weebopedia/public/assets/bleach2.png
  Project139 - Weebopedia/public/assets/logo.png
  Project139 - Weebopedia/public/assets/naruto.jpg
  Project139 - Weebopedia/public/assets/naruto.png
  Project139 - Weebopedia/public/assets/naruto2.png
  Project139 - Weebopedia/public/assets/onePiece.png
  Project139 - Weebopedia/public/assets/onePiece2.png
  Project139 - Weebopedia/public/config/apiUrl.js
  Project139 - Weebopedia/public/next.svg
  Project139 - Weebopedia/public/vercel.svg
  Project139 - Weebopedia/tailwind.config.js
Labels: SWOC, INTERMEDIATE

#520 Added Betting Website
  Project139 - Betting Website/.gitignore
  Project139 - Betting Website/README.md
  Project139 - Betting Website/package-lock.json
  Project139 - Betting Website/package.json
  Project139 - Betting Website/public/index.html
  Project139 - Betting Website/public/manifest.json
  Project139 - Betting Website/public/robots.txt
  Project139 - Betting Website/src/App.css
  Project139 - Betting Website/src/App.js
  Project139 - Betting Website/src/App.test.js
  Project139 - Betting Website/src/components/Footer.js
  Project139 - Betting Website/src/components/Header.js
  Project139 - Betting Website/src/components/hero.js
  Project139 - Betting Website/src/components/home.js
  Project139 - Betting Website/src/fonts/NeueHaasDisplay/NeueHaasDisplayBlack.ttf
  Project139 - Betting Website/src/fonts/NeueHaasDisplay/NeueHaasDisplayBold.ttf
  Project139 - Betting Website/src/fonts/NeueHaasDisplay/NeueHaasDisplayLight.ttf
  Project139 - Betting Website/src/fonts/NeueHaasDisplay/NeueHaasDisplayMediu.ttf
  Project139 - Betting Website/src/fonts/NeueHaasDisplay/NeueHaasDisplayRoman.ttf
  Project139 - Betting Website/src/fonts/Thunder/Thunder-BoldLC.ttf
  Project139 - Betting Website/src/fonts/Thunder/Thunder-MediumLC 500.otf
  Project139 - Betting Website/src/fonts/Thunder/thunder-lc 2.ttf
  Project139 - Betting Website/src/fonts/Thunder/thunder-lc.ttf
  Project139 - Betting Website/src/index.css
  Project139 - Betting Website/src/index.js
  Project139 - Betting Website/src/reportWebVitals.js
  Project139 - Betting Website/src/setupTests.js
  Project139 - Betting Website/tailwind.config.js
  Project139 - Betting Website/yolo.js
Labels: SWOC, INTERMEDIATE

#526 Added memory game file
  memory game/index.html
  memory game/script.js
  memory game/style.css
Labels: SWOC, INTERMEDIATE

#543 western air game added
  Project140 - WesternAirGame/easy.html
  Project140 - WesternAirGame/hard.html
  Project140 - WesternAirGame/img/bg.jpg
  Project140 - WesternAirGame/img/easy.png
  Project140 - WesternAirGame/img/github.png
  Project140 - WesternAirGame/img/hard.png
  Project140 - WesternAirGame/img/home.png
  Project140 - WesternAirGame/img/intro-mobile.jpg
  Project140 - WesternAirGame/img/intro.jpg
  Project140 - WesternAirGame/img/medium.png
  Project140 - WesternAirGame/img/mobile.png
  Project140 - WesternAirGame/img/target.png
  Project140 - WesternAirGame/index.html
  Project140 - WesternAirGame/medium.html
  Project140 - WesternAirGame/script.js
  Project140 - WesternAirGame/sound/click.mp3
  Project140 - WesternAirGame/sound/empty-click.mp3
  Project140 - WesternAirGame/sound/music.mp3
  Project140 - WesternAirGame/styles.css
Labels: SWOC, BEGINNER

#553 FIX #542
  Project145 - Transition-Login-Page/index.html
  Project145 - Transition-Login-Page/proj.css
  Project145 - Transition-Login-Page/proj.js
Labels: SWOC, BEGINNER

#555 feat: added exchange rate calculator
  Project140 - Exchange Rate Calculator/README.md
  Project140 - Exchange Rate Calculator/img/money.png
  Project140 - Exchange Rate Calculator/index.html
  Project140 - Exchange Rate Calculator/script.js
  Project140 - Exchange Rate Calculator/style.css
Labels: SWOC, BEGINNER

#556 feat: added percentage calculator
  Project140 - Percentage Calculator/background.png
  Project140 - Percentage Calculator/index.html
  Project140 - Percentage Calculator/index.js
  Project140 - Percentage Calculator/style.css
Labels: SWOC, BEGINNER

#558 feat: added powerful lyrics searcher
  Project140 - Lyrics Search/index.html
  Project140 - Lyrics Search/readme.md
  Project140 - Lyrics Search/script.js
  Project140 - Lyrics Search/style.css
Labels: SWOC, BEGINNER

#578 Build Creative Education Website #477
  Project125/assets/css/style.css
  Project125/assets/images/Thumbs.db
  Project125/assets/images/about-banner.jpg
  Project125/assets/images/about-shape-1.svg
  Project125/assets/images/about-shape-2.svg
  Project125/assets/images/about-shape-3.png
  Project125/assets/images/about-shape-4.svg
  Project125/assets/images/blog-1.jpg
  Project125/assets/images/blog-2.jpg
  Project125/assets/images/blog-3.jpg
  Project125/assets/images/blog-bg.svg
  Project125/assets/images/blog-shape.png
  Project125/assets/images/category-1.svg
  Project125/assets/images/category-2.svg
  Project125/assets/images/category-3.svg
  Project125/assets/images/category-4.svg
  Project125/assets/images/course-1.jpg
  Project125/assets/images/course-2.jpg
  Project125/assets/images/course-3.jpg
  Project125/assets/images/footer-bg.png
  Project125/assets/images/hero-banner-1.jpg
  Project125/assets/images/hero-banner-2.jpg
  Project125/assets/images/hero-bg.svg
  Project125/assets/images/hero-shape-1.svg
  Project125/assets/images/hero-shape-2.png
  Project125/assets/images/logo-light.svg
  Project125/assets/images/logo.svg
  Project125/assets/images/video-banner.jpg
  Project125/assets/images/video-bg.png
  Project125/assets/images/video-shape-1.png
  Project125/assets/images/video-shape-2.png
  Project125/assets/js/script.js
  Project125/favicon.svg
  Project125/index.html
  Project125/index.txt
  Project125/style-guide.md
Labels: SWOC, INTERMEDIATE

#580 Make Responsive Agency Website #474
  Project Make Responsive Agency 0/assets/css/style.css
  Project Make Responsive Agency 0/assets/images/Thumbs.db
  Project Make Responsive Agency 0/assets/images/about-1.jpg
  Project Make Responsive Agency 0/assets/images/about-2.jpg
  Project Make Responsive Agency 0/assets/images/about-3.jpg
  Project Make Responsive Agency 0/assets/images/blog-1.jpg
  Project Make Responsive Agency 0/assets/images/blog-2.jpg
  Project Make Responsive Agency 0/assets/images/blog-3.jpg
  Project Make Responsive Agency 0/assets/images/blog-4.jpg
  Project Make Responsive Agency 0/assets/images/collection-1.jpg
  Project Make Responsive Agency 0/assets/images/collection-2.jpg
  Project Make Responsive Agency 0/assets/images/collection-3.jpg
  Project Make Responsive Agency 0/assets/images/feature-banner.jpg
  Project Make Responsive Agency 0/assets/images/feature-icon-1.svg
  Project Make Responsive Agency 0/assets/images/feature-icon-2.svg
  Project Make Responsive Agency 0/assets/images/feature-icon-3.svg
  Project Make Responsive Agency 0/assets/images/gallery-1.jpg
  Project Make Responsive Agency 0/assets/images/gallery-2.jpg
  Project Make Responsive Agency 0/assets/images/gallery-3.jpg
  Project Make Responsive Agency 0/assets/images/gallery-4.jpg
  Project Make Responsive Agency 0/assets/images/hero-banner-1.jpg
  Project Make Responsive Agency 0/assets/images/hero-banner-2.jpg
  Project Make Responsive Agency 0/assets/images/hero-shape.png
  Project Make Responsive Agency 0/assets/images/play.svg
  Project Make Responsive Agency 0/assets/images/quote.svg
  Project Make Responsive Agency 0/assets/js/script.js
  Project Make Responsive Agency 0/favicon.svg
  Project Make Responsive Agency 0/index.html
  Project Make Responsive Agency 0/index.txt
  Project Make Responsive Agency 0/readme-images/Thumbs.db
  Project Make Responsive Agency 0/readme-images/desktop.png
  Project Make Responsive Agency 0/style-guide.md
Labels: SWOC, INTERMEDIATE

#610 feat: added meme generator via imgflip api
  Project146 - Meme Generator/index.html
  Project146 - Meme Generator/script.js
  Project146 - Meme Generator/style.css
Labels: SWOC, BEGINNER

#616 feat: added crossword puzzle game
  Project146 - Crossword Puzzle Game/index.html
  Project146 - Crossword Puzzle Game/script.js
  Project146 - Crossword Puzzle Game/style.css
Labels: SWOC, BEGINNER
