Repository SOMNATH0904/DevSphere, pull requests merged in 2025-01, with the labels that each got.

#12 project 2 (snake game)
  Project02/index.html
  Project02/script.js
  Project02/style.css
Labels: SWOC, INTERMEDIATE, SWOC 2024

#15 Implement Stone Paper Scissors Game with Score Tracking
  stone_paper_scissors/first.js
  stone_paper_scissors/index.html
  stone_paper_scissors/style.css
Labels: SWOC, INTERMEDIATE, SWOC 2024

#21 Adding hangman game fixed the #20
  Project6-hangmanGame/HangmanGame/Readme.md
  Project6-hangmanGame/HangmanGame/images/hangman-0.svg
  Project6-hangmanGame/HangmanGame/images/hangman-1.svg
  Project6-hangmanGame/HangmanGame/images/hangman-2.svg
  Project6-hangmanGame/HangmanGame/images/hangman-3.svg
  Project6-hangmanGame/HangmanGame/images/hangman-4.svg
  Project6-hangmanGame/HangmanGame/images/hangman-5.svg
  Project6-hangmanGame/HangmanGame/images/hangman-6.svg
  Project6-hangmanGame/HangmanGame/images/lost.gif
  Project6-hangmanGame/HangmanGame/images/victory.gif
  Project6-hangmanGame/HangmanGame/index.html
  Project6-hangmanGame/HangmanGame/script.js
  Project6-hangmanGame/HangmanGame/style.css
Labels: SWOC, ADVANCE, SWOC 2024

#23 Project7 Fixed Countdown Timer
  Project7 -CountDown Timer/index.html
  Project7 -CountDown Timer/script.js
  Project7 -CountDown Timer/style.css
Labels: SWOC, INTERMEDIATE, SWOC 2024

#25 Add Flappy Bird Game Implementation
  Flappy-bird-main/bottompipe.png
  Flappy-bird-main/flappybird.png
  Flappy-bird-main/flappybirdbg.png
  Flappy-bird-main/index.html
  Flappy-bird-main/toppipe.png
Labels: SWOC, ADVANCE, SWOC 2024

#30 Project 9 : Simple Calculator Fixed
  Project9 - Simple Calculator/index.html
  Project9 - Simple Calculator/script.js
  Project9 - Simple Calculator/styles.css
Labels: SWOC, BEGINNER, SWOC 2025

#33 Add tower game
  Project - TowerGame/index.html
  Project - TowerGame/script.js
  Project - TowerGame/style.css
Labels: SWOC, INTERMEDIATE, SWOC 2025

#49 Tic Tac Toe
  Project12/index.html
  Project12/script.js
  Project12/style.css
Labels: SWOC, BEGINNER, SWOC 2025

#54 Project 13 - Guess random Number
  Project 13 - Guess the random Number Game/index.html
  Project 13 - Guess the random Number Game/script.js
  Project 13 - Guess the random Number Game/styles.css
Labels: SWOC, BEGINNER, SWOC 2025

#57 Animated Cursor
  Project19/index.html
  Project19/script.js
  Project19/style.css
Labels: SWOC, BEGINNER

#69 adding project-20
  Project20-obeysClone/assets/arrow.png
  Project20-obeysClone/assets/d8fa28ee599051ab07588e1d077e320b09ce0cd7 (1).mp4
  Project20-obeysClone/assets/d8fa28ee599051ab07588e1d077e320b09ce0cd7.mp4
  Project20-obeysClone/assets/download (1).svg
  Project20-obeysClone/assets/download.svg
  Project20-obeysClone/assets/favicon.png
  Project20-obeysClone/assets/img1-1.jpg
  Project20-obeysClone/assets/img1-2.jpg
  Project20-obeysClone/assets/img2-1.jpg
  Project20-obeysClone/assets/img2-2.jpg
  Project20-obeysClone/assets/img3-1.jpg
  Project20-obeysClone/assets/img3-2.jpg
  Project20-obeysClone/assets/img4-1.jpg
  Project20-obeysClone/assets/img4-2.jpg
  Project20-obeysClone/fonts/plain-light-webfont.ttf
  Project20-obeysClone/fonts/plain-regular-webfont.ttf
  Project20-obeysClone/fonts/silkserif-lightitalic-webfont.ttf
  Project20-obeysClone/fonts/silkserif-regularitalic-webfont.ttf
  Project20-obeysClone/index.html
  Project20-obeysClone/script.js
  Project20-obeysClone/style.css
Labels: SWOC, ADVANCE

#75 Stock Profit Calculator – Simple Investment Analysis Tool
  PINGPONG_GAME/index.html
  PINGPONG_GAME/script.js
  PINGPONG_GAME/style.css
  Stock-Profit-Calculator/assets/background.jpg
  Stock-Profit-Calculator/assets/stock_calci.jpg
  Stock-Profit-Calculator/index.html
  Stock-Profit-Calculator/script.js
  Stock-Profit-Calculator/style.css
Labels: SWOC, INTERMEDIATE

#86 Add to do list
  Project28-Todolist/app.js
  Project28-Todolist/bin.png
  Project28-Todolist/edit.png
  Project28-Todolist/index.html
  Project28-Todolist/style.css
Labels: SWOC, ADVANCE

#93 Dynamic Typewriter Showcase
  typewriter/typewriter.css
  typewriter/typewriter.html
  typewriter/typewriter.js
Labels: SWOC, INTERMEDIATE

#97 Adding Project-32
  Project32-ExpenseTracker/README.md
  Project32-ExpenseTracker/Webapp/index.html
  Project32-ExpenseTracker/Webapp/script.js
  Project32-ExpenseTracker/Webapp/style.css
  Project32-ExpenseTracker/preview.png
  Project32-ExpenseTracker/wall.jpeg
Labels: SWOC, ADVANCE

#101 responsiveness of stone paper scissor is ready issue #36
  Project04 - StonePaperScissor/style.css
Labels: SWOC, BEGINNER

#106 adding Project35
  Project35-AdminDashboard/dashboard/dashboard.css
  Project35-AdminDashboard/dashboard/dashboard.html
  Project35-AdminDashboard/index.html
  Project35-AdminDashboard/script.js
  Project35-AdminDashboard/style.css
Labels: SWOC, ADVANCE

#112 Add toggle button
  Project31 - PlantWebsite/plant.css
  Project31 - PlantWebsite/plant.html
Labels: SWOC, INTERMEDIATE

#114 TextToSpeechConverter FIXES #78
  Project38 - TextToSpeechConverter/README.md
  Project38 - TextToSpeechConverter/index.html
  Project38 - TextToSpeechConverter/script.js
  Project38 - TextToSpeechConverter/style.css
Labels: SWOC, ADVANCE

#121 Adding project38
  Project38-PocketImage/index.html
  Project38-PocketImage/script.js
  Project38-PocketImage/style.css
  Project39-QRCodeGenerator/index.html
  Project39-QRCodeGenerator/script.js
  Project39-QRCodeGenerator/style.css
  Project40-FlashiThings/index.html
  Project40-FlashiThings/script.js
  Project40-FlashiThings/style.css
Labels: SWOC, INTERMEDIATE

#124 Code jump space project
  Code Jump Space/doodlejumpbg.png
  Code Jump Space/doodler-left.png
  Code Jump Space/doodler-right.png
  Code Jump Space/index.html
  Code Jump Space/platform-broken.png
  Code Jump Space/platform.png
  Code Jump Space/script.js
  Code Jump Space/style.css
Labels: SWOC, ADVANCE

#128 Project 38 - LinkedIn Clone
  Project38-LinkedInClone/images/chat.png
  Project38-LinkedInClone/images/clap.png
  Project38-LinkedInClone/images/comment.png
  Project38-LinkedInClone/images/connect.png
  Project38-LinkedInClone/images/cover-pic.png
  Project38-LinkedInClone/images/display.png
  Project38-LinkedInClone/images/down-arrow.png
  Project38-LinkedInClone/images/event.png
  Project38-LinkedInClone/images/feedback.png
  Project38-LinkedInClone/images/google.png
  Project38-LinkedInClone/images/group.png
  Project38-LinkedInClone/images/hashtag.png
  Project38-LinkedInClone/images/help.png
  Project38-LinkedInClone/images/home.png
  Project38-LinkedInClone/images/items.png
  Project38-LinkedInClone/images/jobs.png
  Project38-LinkedInClone/images/like.png
  Project38-LinkedInClone/images/logo.png
  Project38-LinkedInClone/images/logout.png
  Project38-LinkedInClone/images/love.png
  Project38-LinkedInClone/images/message.png
  Project38-LinkedInClone/images/mi-logo.png
  Project38-LinkedInClone/images/microsoft.png
  Project38-LinkedInClone/images/mit.png
  Project38-LinkedInClone/images/more.png
  Project38-LinkedInClone/images/network.png
  Project38-LinkedInClone/images/north.png
  Project38-LinkedInClone/images/notification.png
  Project38-LinkedInClone/images/photo.png
  Project38-LinkedInClone/images/post-image-1.png
  Project38-LinkedInClone/images/post-image-2.png
  Project38-LinkedInClone/images/post-image-3.png
  Project38-LinkedInClone/images/post-image-4.png
  Project38-LinkedInClone/images/premium.png
  Project38-LinkedInClone/images/recent.png
  Project38-LinkedInClone/images/right-arrow.png
  Project38-LinkedInClone/images/search.png
  Project38-LinkedInClone/images/send.png
  Project38-LinkedInClone/images/setting.png
  Project38-LinkedInClone/images/share.png
  Project38-LinkedInClone/images/slack.png
  Project38-LinkedInClone/images/stanford.png
  Project38-LinkedInClone/images/thumbsup.png
  Project38-LinkedInClone/images/user-1.png
  Project38-LinkedInClone/images/user-2.png
  Project38-LinkedInClone/images/user-3.png
  Project38-LinkedInClone/images/user-4.png
  Project38-LinkedInClone/images/user-5.png
  Project38-LinkedInClone/images/video.png
  Project38-LinkedInClone/index.html
  Project38-LinkedInClone/style.css
Labels: SWOC, ADVANCE

#130 Add Typing Speed Test Game with Dynamic WPM Calculation
  TypingSpeed/index.html
  TypingSpeed/script.js
  TypingSpeed/styles.css
Labels: SWOC, INTERMEDIATE

#141 QRCodeGenerator FIX #77
  Project39 - QRCodeGenerator/README.md
  Project39 - QRCodeGenerator/index.html
  Project39 - QRCodeGenerator/script.js
  Project39 - QRCodeGenerator/style.css
Labels: SWOC, INTERMEDIATE

#144 Simple Expense Tracker App
  Project47 - Expanse Tracker/.gitignore
  Project47 - Expanse Tracker/README.md
  Project47 - Expanse Tracker/eslint.config.js
  Project47 - Expanse Tracker/index.html
  Project47 - Expanse Tracker/package-lock.json
  Project47 - Expanse Tracker/package.json
  Project47 - Expanse Tracker/postcss.config.js
  Project47 - Expanse Tracker/public/vite.svg
  Project47 - Expanse Tracker/src/App.css
  Project47 - Expanse Tracker/src/App.jsx
  Project47 - Expanse Tracker/src/assets/react.svg
  Project47 - Expanse Tracker/src/components/ExpenseForm.jsx
  Project47 - Expanse Tracker/src/components/ExpenseList.jsx
  Project47 - Expanse Tracker/src/index.css
  Project47 - Expanse Tracker/src/main.jsx
  Project47 - Expanse Tracker/tailwind.config.js
  Project47 - Expanse Tracker/vite.config.js
Labels: SWOC, ADVANCE

#154 Task Manager Adding
  Project48-TaskManager/index.html
  Project48-TaskManager/script.js
  Project48-TaskManager/style.css
Labels: SWOC, INTERMEDIATE

#151 Star Rating Webpage
  Star Rating/index.html
  Star Rating/script.js
  Star Rating/style.css
Labels: SWOC, BEGINNER

#170 Play the quiz
  Project14 - Play quiz/index.html
  Project14 - Play quiz/questions.js
  Project14 - Play quiz/readme.md
  Project14 - Play quiz/script.js
  Project14 - Play quiz/style.css
Labels: SWOC, BEGINNER

#173 Add Resume Studio
  Project 47-Resume Studio/index.html
  Project 47-Resume Studio/script.js
  Project 47-Resume Studio/style.css
Labels: SWOC, ADVANCE

#176 Add Insect catchy game
  Project47 - Insect-Catch-Game/index.html
  Project47 - Insect-Catch-Game/script.js
  Project47 - Insect-Catch-Game/style.css
Labels: SWOC, BEGINNER

#179 added GitHub Profile Finder
  Project47-GitHub_Profile_Finder/index.html
  Project47-GitHub_Profile_Finder/index.js
  Project47-GitHub_Profile_Finder/style.css
Labels: SWOC, INTERMEDIATE

#180 Added random quote generator
  Project47-RandomQuoteGenerator/index.html
  Project47-RandomQuoteGenerator/index.js
  Project47-RandomQuoteGenerator/style.css
Labels: SWOC, BEGINNER

#186 add slide puzzle game
  Project47 - Slide puzzle/Slide puzzle Game/1.jpg
  Project47 - Slide puzzle/Slide puzzle Game/10.jpg
  Project47 - Slide puzzle/Slide puzzle Game/2.jpg
  Project47 - Slide puzzle/Slide puzzle Game/3.jpg
  Project47 - Slide puzzle/Slide puzzle Game/4.jpg
  Project47 - Slide puzzle/Slide puzzle Game/5.jpg
  Project47 - Slide puzzle/Slide puzzle Game/6.jpg
  Project47 - Slide puzzle/Slide puzzle Game/7.jpg
  Project47 - Slide puzzle/Slide puzzle Game/8.jpg
  Project47 - Slide puzzle/Slide puzzle Game/9.jpg
  Project47 - Slide puzzle/Slide puzzle Game/img/logo.png
  Project47 - Slide puzzle/Slide puzzle Game/index.html
  Project47 - Slide puzzle/Slide puzzle Game/puzzle.css
  Project47 - Slide puzzle/Slide puzzle Game/puzzle.js
Labels: SWOC, BEGINNER

#188 Add Hand Gesture Controlled Space Shooter Game
  Galactic Shooter/GalacticShooter.py
  Galactic Shooter/README.md
  Galactic Shooter/background.png
  Galactic Shooter/background_music.mp3
  Galactic Shooter/bullet.png
  Galactic Shooter/enemy_ship.png
  Galactic Shooter/explosion.wav
  Galactic Shooter/game_over.wav
  Galactic Shooter/icon.png
  Galactic Shooter/player_ship.png
  Galactic Shooter/power_up.png
  Galactic Shooter/power_up.wav
  Galactic Shooter/shoot.wav
  Galactic Shooter/splash.png
  Galactic Shooter/test.py
Labels: SWOC, INTERMEDIATE

#189 Improve Input Validation
  Project33 - ExpenseTracker/Webapp/script.js
Labels: SWOC, BEGINNER

#190 Enhancements and Bug Fixes
  Project26 - PingPongGame/script.js
Labels: SWOC, BEGINNER

#191 Improve Password Generator Logic
  Project22 - PasswordGenerator/src/App.jsx
Labels: SWOC, BEGINNER

#192 Added Zomato Clone
  Project 48 - Zomato Clone/accordion.js
  Project 48 - Zomato Clone/app.css
  Project 48 - Zomato Clone/explore.css
  Project 48 - Zomato Clone/footer.css
  Project 48 - Zomato Clone/images/favicon.ico
  Project 48 - Zomato Clone/images/india.png
  Project 48 - Zomato Clone/images/logo.png
  Project 48 - Zomato Clone/index.css
  Project 48 - Zomato Clone/index.html
  Project 48 - Zomato Clone/main.css
  Project 48 - Zomato Clone/nav.css
  Project 48 - Zomato Clone/top.css
Labels: SWOC, BEGINNER

#194 Fix Time Drift and Improve Theme/Timezone Toggle Functionality
  Project15 - DigitalClock/script.js
Labels: SWOC, INTERMEDIATE

#195 Code Improvements and Fixes for JavaScript Features
  Project31 - PlantWebsite/script.js
Labels: SWOC, INTERMEDIATE

#196 Code Enhancement and Bug Fixes
  Project16 - TicTacToe/script.js
Labels: SWOC, BEGINNER

#197 mprove UI and Fix Functionalities in "ManageDailyTask"
  Project05 - ManageDailyTasks/index.html
  Project05 - ManageDailyTasks/todolist.css
  Project05 - ManageDailyTasks/todolist.js
Labels: SWOC, BEGINNER

#200 Adding Text Saver Extension
  Project48-Text Saver Extension/Text_Saver_Ext-main/content.js
  Project48-Text Saver Extension/Text_Saver_Ext-main/popup.html
  Project48-Text Saver Extension/Text_Saver_Ext-main/popup.js
  Project48-Text Saver Extension/background.js
  Project48-Text Saver Extension/content.js
Labels: SWOC, INTERMEDIATE

#201 Project48 - Language Learning Flashcards
  Project48 - LanguageLearningFlashcards/README.md
  Project48 - LanguageLearningFlashcards/index.html
  Project48 - LanguageLearningFlashcards/script.js
  Project48 - LanguageLearningFlashcards/style.css
Labels: SWOC, INTERMEDIATE

#202 Added Frontend Pages and Backend Code for सेवाSHARE Platform (Collaborated with Anshumali Sharma @anshumali19)
  Project49 - सेवाSHARE(Emergency Resources Exchange)/certificate.html
  Project49 - सेवाSHARE(Emergency Resources Exchange)/css/style.css
  Project49 - सेवाSHARE(Emergency Resources Exchange)/css/style1.css
  Project49 - सेवाSHARE(Emergency Resources Exchange)/css/style2.css
  Project49 - सेवाSHARE(Emergency Resources Exchange)/css/style3.css
  Project49 - सेवाSHARE(Emergency Resources Exchange)/css/style4.css
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/actionaid.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/akshay patra.jpg
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/care.jpg
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/goonj.jpg
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/habitat human.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/ircs.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/oxfam.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/ramakrishna.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/reward.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/seva.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/seva1.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/images/vivekananda.png
  Project49 - सेवाSHARE(Emergency Resources Exchange)/index.html
  Project49 - सेवाSHARE(Emergency Resources Exchange)/js/app.js
  Project49 - सेवाSHARE(Emergency Resources Exchange)/login.html
  Project49 - सेवाSHARE(Emergency Resources Exchange)/ngo.html
  Project49 - सेवाSHARE(Emergency Resources Exchange)/package-lock.json
  Project49 - सेवाSHARE(Emergency Resources Exchange)/package.json
  Project49 - सेवाSHARE(Emergency Resources Exchange)/reg.html
  Project49 - सेवाSHARE(Emergency Resources Exchange)/server.js
Labels: SWOC, ADVANCE

#208 Project 69 - Scroll Dark run Game
  Project 69 - Scroll Dark Run Game/Grass.png
  Project 69 - Scroll Dark Run Game/bg-forest.jpg
  Project 69 - Scroll Dark Run Game/bird.png
  Project 69 - Scroll Dark Run Game/bush-monster.png
  Project 69 - Scroll Dark Run Game/bush.png
  Project 69 - Scroll Dark Run Game/go-right.png
  Project 69 - Scroll Dark Run Game/house.png
  Project 69 - Scroll Dark Run Game/idle-back.png
  Project 69 - Scroll Dark Run Game/idle.png
  Project 69 - Scroll Dark Run Game/index.html
  Project 69 - Scroll Dark Run Game/main.js
  Project 69 - Scroll Dark Run Game/pillar.png
  Project 69 - Scroll Dark Run Game/running-back.png
  Project 69 - Scroll Dark Run Game/running.png
  Project 69 - Scroll Dark Run Game/saw.png
  Project 69 - Scroll Dark Run Game/styles.css
  Project 69 - Scroll Dark Run Game/trees-01.png
  Project 69 - Scroll Dark Run Game/trees-02.png
  Project 69 - Scroll Dark Run Game/trees-03.png
  Project 69 - Scroll Dark Run Game/trees-1.png
Labels: SWOC, BEGINNER

#210 Replaced eval with a Safer Calculation Method
  Project09 - SimpleCalculator/script.js
Labels: SWOC, BEGINNER

#212 Commited bubble game
  Project71 - Bubble game/index.html
  Project71 - Bubble game/script.js
  Project71 - Bubble game/styles.css
Labels: SWOC, BEGINNER

#213 added digital clock
  Project71-DigitalClock/index.html
  Project71-DigitalClock/index.js
  Project71-DigitalClock/style.css
Labels: SWOC, BEGINNER

#215 added password strength indicator
  Project73-PasswordStrengthIndicator/index.html
  Project73-PasswordStrengthIndicator/index.js
  Project73-PasswordStrengthIndicator/style.css
Labels: SWOC, BEGINNER

#216 Improved Quiz Application UI (Logo and Favicon addition) and Code Structure
  Project14 - QuizAppTimer/favicon.png
  Project14 - QuizAppTimer/index.html
  Project14 - QuizAppTimer/logo.png
  Project14 - QuizAppTimer/script.js
Labels: SWOC, BEGINNER

#217 Project 73 N Queens game
  Project 73 - NQueens Game/index.html
  Project 73 - NQueens Game/script.js
  Project 73 - NQueens Game/style.css
Labels: SWOC, BEGINNER

#223 added drawing app
  Project73-DrawingApp/index.html
  Project73-DrawingApp/index.js
  Project73-DrawingApp/style.css
Labels: SWOC, INTERMEDIATE

#224 added auto text effect
  Project73-AutoTextEffect/index.html
  Project73-AutoTextEffect/script.js
  Project73-AutoTextEffect/style.css
Labels: SWOC, BEGINNER

#225 added emoji switcher
  Project73-EmojiSwitcher/index.html
  Project73-EmojiSwitcher/script.js
  Project73-EmojiSwitcher/style.css
Labels: SWOC, BEGINNER

#226 Palindrome Generator Fixed
  Project 74 - Palindrome Generator/index.html
  Project 74 - Palindrome Generator/script.js
  Project 74 - Palindrome Generator/style.css
Labels: SWOC, BEGINNER

#231 Add spotify_clone
  Project73 -Spotify_Clone/img-assests/album_icon1.png
  Project73 -Spotify_Clone/img-assests/album_icon2.png
  Project73 -Spotify_Clone/img-assests/album_picture.jpeg
  Project73 -Spotify_Clone/img-assests/backward_icon.png
  Project73 -Spotify_Clone/img-assests/card1img.jpeg
  Project73 -Spotify_Clone/img-assests/card2img.jpeg
  Project73 -Spotify_Clone/img-assests/card3img.jpeg
  Project73 -Spotify_Clone/img-assests/card4img.jpeg
  Project73 -Spotify_Clone/img-assests/card5img.jpeg
  Project73 -Spotify_Clone/img-assests/card6img.jpeg
  Project73 -Spotify_Clone/img-assests/controld_icon2.png
  Project73 -Spotify_Clone/img-assests/controls_icon1.png
  Project73 -Spotify_Clone/img-assests/controls_icon3.png
  Project73 -Spotify_Clone/img-assests/controls_icon4.png
  Project73 -Spotify_Clone/img-assests/controls_icon5.png
  Project73 -Spotify_Clone/img-assests/forward_icon.png
  Project73 -Spotify_Clone/img-assests/library_icon.png
  Project73 -Spotify_Clone/img-assests/logo.png
  Project73 -Spotify_Clone/img-assests/play_musicbar.png
  Project73 -Spotify_Clone/img-assests/player_icon1.png
  Project73 -Spotify_Clone/img-assests/player_icon2.png
  Project73 -Spotify_Clone/img-assests/player_icon3.png
  Project73 -Spotify_Clone/img-assests/player_icon4.png
  Project73 -Spotify_Clone/img-assests/player_icon5.png
  Project73 -Spotify_Clone/index.html
  Project73 -Spotify_Clone/style.css
Labels: SWOC, INTERMEDIATE
